version: '3.2'

services:

  service:
    image: digigladd/helloan/publication:1.0
    environment:
      - APPLICATION_SECRET=jenesuispasunheros
      - HOSTNAME=service
      - CAS_NATIVE=tcp://${CAS}:9042
      - KAFKA_NATIVE=tcp://${KAFKA}:9092
      - CAS=${CAS}
    networks:
      - default
    ports:
      - "127.0.0.1:9003:9000"

networks:
  default:
    external:
      name: digigladd
