version: '3.2'

services:

  service:
    image: digigladd/helloan/seance:1.0
    environment:
      - APPLICATION_SECRET=jenesuispasunheros
      - HOSTNAME=service
      - CAS_NATIVE=tcp://${CAS}:9042
      - KAFKA_NATIVE=tcp://${KAFKA}:9092
      - CAS=${CAS}
    volumes:
      - ../datasets:/opt/docker/datasets
      - ../logs:/opt/docker/logs
    networks:
      - default
    ports:
      - "9000"

networks:
  default:
    external:
      name: digigladd
