version: '3.2'

services:

  service:
    image: digigladd/helloan/seance:1.0
    container_name: seance
    environment:
      - CAS_NATIVE=tcp://reactivebox_cas_native:9042
      - KAFKA_NATIVE=tcp://reactivebox_kafka:9092
      - APPLICATION_SECRET=jenesuispasunheros
      - HOSTNAME=seance
    networks:
      - default
    ports:
      - "127.0.0.1:9001:9000"

networks:
  default:
    external:
      name: digigladd
